stages:
  - createAciCertUser
  - fabDiscoverAndBaseConfig
  - portsAndVmmIntegration
  - createTenant
  - addToNso

image: jc3943/ubuntu:5.30.22

variables:
  varPath: vars/$CI_COMMIT_REF_NAME
  apicInventory: creds/inv-$CI_COMMIT_REF_NAME
  apicInventoryx509: $apicInventory-x509

createAciCertUser:
  stage: createAciCertUser
  script:
    - ansible-playbook -i $apicInventory aci/aciCreate-cert-userv3.yml
  only:
    - sandbox

fabDiscoverAndBaseConfig:
  stage: fabDiscoverAndBaseConfig
  script:
    - python3 aci/aciBuildInventory.py
    - ansible-playbook -i $apicInventoryx509 aci/aciBuildFabric.yml --extra-vars="@$varPath/aci/switch-inventory.yaml"
    - ansible-playbook -i $apicInventoryx509 aci/aciVmmDomain.yml --extra-vars="@$varPath/aci/switch-inventory.yaml"
  only:
    - sandbox

portsAndVmmIntegration:
  stage: portsAndVmmIntegration
  script:
    - python3 aci/aciCreate_port_yaml.py
    - ansible-playbook -i $apicInventoryx509 aci/aciIntf-create.yml --extra-vars="@$varPath/aci/aci-ports.yaml"
    - ansible-playbook -i $apicInventoryx509 aci/aciVmmDomain.yml --extra-vars="@$varPath/aci/switch-inventory.yaml"
  only:
    - sandbox

createTenant:
  stage: createTenant
  script:
    - python3 aci/aciCreate_yaml_from_csv_v4.3.py -i $varPath/aci/tenant.csv -o  $varPath/aci/tenant.yaml
    - ansible-playbook -i $apicInventoryx509 aci/aciMake-tenants-x509v4.3.yml --extra-vars="@$varPath/aci/tenant.yaml"
    - ansible-playbook -i $apicInventoryx509 aci/aciJsonLoad.yml -e json_payload="../$varPath/aci/L3-Out.json"
    - python3 ./aci/aciCreate_yaml_from_csv_v4.3.py -i $varPath/aci/bare-metal-aep.csv -o $varPath/aci/bare-metal-aep.yaml
    - ansible-playbook -i $apicInventoryx509 aci/aep-epg-bm.yml --extra-vars="@$varPath/aci/bare-metal-aep.yaml"
    - ansible-playbook -i $apicInventoryx509 aci/aciDhcpRelay.yml
  only:
    - sandbox

addToNso:
  stage: addToNso
  script:
    - ansible-playbook -i localhost nso/nsoAddAuthGrp.yml --extra-vars="@$varPath/nso/nso-Specs.yaml"
    - ansible-playbook -i localhost nso/nsoAddApic.yml --extra-vars="@$varPath/nso/nso-Specs.yaml"
  only:
    - sandbox