---
# Jeff Comer
# Ansible Playbook to map baremetal epg's to appropriate aep
- name: MAP BAREMETAL EPGs TO AEP
  hosts: apic
  connection: local
  gather_facts: False

  tasks:
    - read_csv:
        path: ../$varPath/aci/tenant.csv
      register: tenantList

    - name: TASK - Map EPG to AEP
      cisco.aci.aci_aep_to_epg:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        private_key: ../creds/ansible.key
        state: "present"
        validate_certs: False
        tenant: "{{ aep.tenant }}"
        aep: "{{ aep.aep }}"
        ap: "{{ aep.appProfile }}"
        epg: "{{ aep.epg }}"
        encap_id: "{{ aep.vlanEncaps }}"
        interface_mode: "{{ aep.mode }}"
      loop: "{{ tenantList.list }}"
      loop_control:
        loop_var: aep
      when: (aep.aep != "NA")
      tags: bm