---
- hosts: localhost
  name: Deploy an ubuntu ova to an ESXi Host
  gather_facts: false
  vars: 
    esxi_username: 'root'
    esxi_password: 'DEVP@ssw0rd'
    esxi_host: '172.16.115.11'
    vcenter_hostname: '172.16.14.137'
    vcenter_password: 'DEVP@ssw0rd'
    vcsa_user: 'administrator@vsphere.local'
    vcsa_pw: 'DEVP@ssw0rd'
    domain: 'devlab.lab.com'
    pubkey: 'ecdsa-sha2-nistp521 ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAHq28PeSRKuZn/dnuA7SQJsJ0ka0eEnGItNqZdW/5zOhe7AzQ7KYYo0mVGrATXZFFIlRm2vELbh9/tOegzhyyGuuwE4wmhE7r+9/a65A2wuZ6+Wx0X04CwdW1Ityh+Gq/aSv338BuMeyznsfIyVEuGEdbczZMVts/HdnIUAOmOrLQAirQ== dcloud@dcloud'
    searchpath: "devlab.lab.com"
    datastore: 'sandbox'
    datacenter: 'sandbox'
    cluster: 'sandbox'
    networks: 'Storage Controller Management Network'
    ubuntu_ova_name: jammy-server-cloudimg-amd64.ova
    ubuntu_ova_file: '/tmp/{{ ubuntu_ova_name }}'
    nfs_file_browser_url: "http://172.16.10.124:8005"
    nfs_file_browser_user: "admin"
    nfs_file_browser_password: "admin"
    nfs_file_url: '/api/raw/00-Software/utils/{{ ubuntu_ova_name }}'

  tasks:

  - name: Authenticate to the nfs file browser
    uri:
      url: '{{ nfs_file_browser_url }}/api/login'
      method: POST
      body_format: json
      body: '{"username":"{{ nfs_file_browser_user }}","password":"{{ nfs_file_browser_password }}","recaptcha":""}'
      headers:
        Content-Type: "application/json"
        Accept: "application/json"
      return_content: yes
      validate_certs: no
      status_code: 200, -1
    register: auth_res

  - name: Download the file
    get_url:
      url: '{{ nfs_file_browser_url }}/api/raw/00-Software/utils/{{ ubuntu_ova_name }}?auth={{ auth_res.content  }}'
      dest: '/tmp/{{ ubuntu_ova_name }}'

  - read_csv:
      path: ../$varPath/aci/tenant.csv
    register: tenantlist
    tags: canary

  - vmware_deploy_ovf:
      hostname: '{{ esxi_host }}'
      username: '{{ esxi_username }}'
      password: '{{ esxi_password }}'
      name: 'ubuntu-templ'
      ovf: '{{ ubuntu_ova_file }}' 
      wait_for_ip_address: false
      validate_certs: no
      inject_ovf_env: true
      power_on: false
      datastore: '{{ datastore }}'
      networks: "{u'Network 1':u'{{ networks }}'}"
      properties:
        instance-id: 'ubuntu-templ'
        hostname: 'ubuntu-templ'
        public-keys: '{{ pubkey}}'
        password: '{{ esxi_password }}'

  - name: TASK - Create Ubuntu Template
    community.vmware.vmware_guest:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcsa_user }}'
      password: '{{ vcsa_pw }}'
      validate_certs: no
      template: "ubuntu-templ"
      name: 'ubuntu-templ'
      folder: /
      datacenter: '{{ datacenter }}'
      cluster: '{{ cluster }}'
      is_template: true

  - name: TASK - Create Test VMs from template
    community.vmware.vmware_guest:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcsa_user }}'
      password: '{{ vcsa_pw }}'
      validate_certs: no
      template: "ubuntu-templ"
      name: 'ubuntu-{{ vms.epg }}'
      folder: /
      datacenter: '{{ datacenter }}'
      cluster: '{{ cluster }}'
      networks:
        - name: "{{ vms.tenant }}|{{ vms.appProfile }}|{{ vms.epg }}"
          type: dhcp
          connected: yes
          start_connected: yes
      state: poweredon
    loop: "{{ tenantlist.list }}"
    loop_control:
        loop_var: vms
    when: (vms.domainType == "vmm" and vms.dhcpRelay != "NA")
