---
#Jeff Comer
#Ansible playbook to add devices to NSO

- hosts: localhost
  gather_facts: no

  tasks:
  - name: CREATE DEVICE IN NSO
    cisco.nso.nso_config:
      url: "{{ item.nsoUrl }}"
      username: admin
      password: admin
      data:
        tailf-ncs:devices:
          device:
           - address: "{{ item.fmcAddress }}"
             description: CONFIGURED BY ANSIBLE!
             name: "{{ item.fmcName }}"
             authgroup: "dcloud-creds"
             local-user: admin
             device-type:
               generic:
                 ned-id: "cisco-fmc-gen-1.6"
             ned-settings:
               tailf-ned-cisco-fmc-meta:cisco-fmc:
                 cisco-fmc-connection:
                   ssl:
                     accept-any: true
             ssh:
               host-key-verification: "none"
             port: "443"
             state:
               admin-state: "unlocked"
    with_items: "{{ nsospecs }}"

  - name: Fetch ssh host keys
    cisco.nso.nso_action:
       url: "{{ item.nsoUrl }}"
       username: admin
       password: admin
       path: /ncs:devices/fetch-ssh-host-keys
       input: {}
    with_items: "{{ nsospecs }}"

  - name: Connect to Device
    cisco.nso.nso_action:
       url: "{{ item.nsoUrl }}"
       username: admin
       password: admin
       path: /ncs:devices/device{"{{ item.apicName }}"}/connect
       input: {}
    with_items: "{{ nsospecs }}"

  - name: Sync From Device
    cisco.nso.nso_action:
       url: "{{ item.nsoUrl }}"
       username: admin
       password: admin
       path: /ncs:devices/device{"{{ item.apicName }}"}/sync-from
       input: {}
    with_items: "{{ nsospecs }}"