---
#Jeff Comer
#Ansible playbook to add devices to NSO

- hosts: localhost
  gather_facts: no

  tasks:
  - name: CREATE DEVICE IN NSO
    cisco.nso.nso_config:
      url: "{{ item.nsoUrl }}"
      username: admin
      password: admin
      data:
        tailf-ncs:devices:
          device:
           - address: "{{ item.apicAddress }}"
             description: CONFIGURED BY ANSIBLE!
             name: "{{ item.apicName }}"
             authgroup: "dcloud-creds"
             local-user: admin
             device-type:
               generic:
                 ned-id: "cisco-apicdc-gen-3.18"
             ned-settings:
               tailf-ned-cisco-apicdc-meta:cisco-apicdc:
                 config-path: "/root/aci"
                 local-host: False
                 host: "198.18.134.150"
                 user-name: "root"
                 user-password: "C1sco12345"
             ssh:
               host-key-verification: "none"
             port: "443"
             state:
               admin-state: "unlocked"
    with_items: "{{ nsospecs }}"

  - name: Fetch ssh host keys
    cisco.nso.nso_action:
       url: "{{ item.nsoUrl }}"
       username: admin
       password: admin
       path: /ncs:devices/fetch-ssh-host-keys
       input: {}
    with_items: "{{ nsospecs }}"

  - name: Connect to Device
    cisco.nso.nso_action:
       url: "{{ item.nsoUrl }}"
       username: admin
       password: admin
       path: /ncs:devices/device{"{{ item.apicName }}"}/connect
       input: {}
    with_items: "{{ nsospecs }}"

  - name: Sync From Device
    cisco.nso.nso_action:
       url: "{{ item.nsoUrl }}"
       username: admin
       password: admin
       path: /ncs:devices/device{"{{ item.apicName }}"}/sync-from
       input: {}
    with_items: "{{ nsospecs }}"